import { Signika } from "next/font/google";
import "./globals.css";

const signika = Signika({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Divyesh Resume",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${signika.className} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
